### ISSUE TITLE
Blog URL broken

### ISSUE THREAD

**Issue by riteshpuj2013** [dennyzhang/cheatsheet-kubernetes-A4#2]
Your blog URL is broken.
Blog URL: https://cheatsheet.dennyzhang.com/cheatsheet-kubernetes
![screenshot from 2018-08-20 15-44-24](https://user-images.githubusercontent.com/3633494/44334708-f3102400-a48f-11e8-84de-5d6b20b7b4ae.png)

**Comment by dennyzhang** [comment]
@riteshpuj2013 , you're right. Fixed.

Thanks a lot for the help. And also the PR!
