### ISSUE TITLE
Command line examples listed in PDF version run-off page margin

### ISSUE THREAD

**Issue by jayachar88** [dennyzhang/cheatsheet-kubernetes-A4#5]
Entry such as:

Set namespace preference kubectl config set-context $(kubectl config current-context) --namespace=<

Seems to runoff the page boundary and is perhaps truncated in the PDF version. Would be nice to have it pretty-printed with line wrap enabled.

**Comment by dennyzhang** [comment]
@jayachar88 , thanks for reporting that.

I have made cosmetic change, which should resolve most of the problems.

To enable line wrap, I might need to patch org-mode elisp for the pdf rendering. That would take some time.
